#!/bin/bash

touch 1.log

matches=$(grep 'WARN' $1)
for match in "${matches[@]}"; do
	echo "$match" >> "./1.log"
done

matches=$(grep 'ERROR' $1)
for match in "${matches[@]}"; do
	echo "$match" >> "./1.log"
done
