#!/bin/bash

echo "Select action:"

echo "1. Start nano"
echo "2. Start vi"
echo "3. Start links"

printf "> "
read

case $REPLY in
	"1")
		nano
		;;
	"2")
		vi
		;;
	"3")
		links
		;;
	*)
		echo "Error: invalid action."
esac
