#!/bin/bash

PROCESSES=$(ls /proc | grep -E '[[:digit:]]+')
MEMPID=''

for PID in $PROCESSES; do
  MEM=$(cat /proc/$PID/status 2>/dev/null |
    grep 'VmRSS' |
    awk '{ print $2 }')
  if [ -z "$MEM" ]; then
    continue
  fi
  MEMPID="$MEMPID$(printf "%s\t%s\n" $MEM $PID)\n"
done

echo -e $MEMPID |
  sort -nr |
  head -n 1 |
  awk '{ printf "PID: %s\nMEM: %s\n", $2, $1}'
